sonar.organization=dmgodoy
sonar.projectKey=dmgodoy_java-test

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=.
